name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Ou a branch que você usa para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar arquivo de chave SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy para EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@54.236.37.216 << 'EOF'
            cd ~/clintia-backend
            git pull origin main  # Atualiza o código
            npm install  # Instala dependências
            npm run build  # Compila o TypeScript (gera a pasta dist)
            pm2 restart clintia-backend --name "clintia-backend" --interpreter node -- dist/index.js
          EOF